### ISSUE TITLE
Crawler data needs to be connected to API

### ISSUE THREAD

**Issue by mosspilot** [mosspilot/GraphicalWebCrawler#1]
It doesn't appear that the crawler is connected to the API... yet.

**Comment by rneh** [comment]
Yea, I thought you were going to do that. I just put the output in the same format as the API. Will that work? Or do you need me to do something else with the output?

**Comment by mosspilot** [comment]
Yeah I plan on doing it after our meeting so I can better understand your code and where Michael is at with his...

**Comment by mosspilot** [comment]
This is done
